export const BUTTON_TYPES = {
  PRIMARY_SMALL_FILL: 'PRIMARY_SMALL_FILL',
  PRIMARY_SMALL_OUTLINE: 'PRIMARY_SMALL_OUTLINE',
  PRIMARY_SMALL_LINK: 'PRIMARY_SMALL_LINK',

  SECONDARY_SMALL_FILL: 'SECONDARY_SMALL_FILL',
  SECONDARY_SMALL_OUTLINE: 'SECONDARY_SMALL_OUTLINE',
  SECONDARY_SMALL_LINK: 'SECONDARY_SMALL_LINK',
};
