import {
  PLFill,
  PLOutline,
  PLDisable,
  PSFill,
  PSOutline,
  PSDisable,
  PSLink,
  SLFill,
  SLOutline,
  SLDisable,
  SSFill,
  SSOutline,
  SSDisable,
  SSLink,
} from './button.styles';

export const BUTTON_TYPES = {
  PRIMARY_LARGE_FILL: 'PRIMARY_LARGE_FILL',
  PRIMARY_LARGE_OUTLINE: 'PRIMARY_LARGE_OUTLINE',
  PRIMARY_LARGE_DISABLE: 'PRIMARY_LARGE_DISABLE',

  PRIMARY_SMALL_FILL: 'PRIMARY_SMALL_FILL',
  PRIMARY_SMALL_OUTLINE: 'PRIMARY_SMALL_OUTLINE',
  PRIMARY_SMALL_DISABLE: 'PRIMARY_SMALL_DISABLE',
  PRIMARY_SMALL_LINK: 'PRIMARY_SMALL_LINK',

  SECONDARY_LARGE_FILL: 'SECONDARY_LARGE_FILL',
  SECONDARY_LARGE_OUTLINE: 'SECONDARY_LARGE_OUTLINE',
  SECONDARY_LARGE_DISABLE: 'SECONDARY_LARGE_DISABLE',

  SECONDARY_SMALL_FILL: 'SECONDARY_SMALL_FILL',
  SECONDARY_SMALL_OUTLINE: 'SECONDARY_SMALL_OUTLINE',
  SECONDARY_SMALL_DISABLE: 'SECONDARY_SMALL_DISABLE',
  SECONDARY_SMALL_LINK: 'SECONDARY_SMALL_LINK',
};

const getButton = (buttonType) =>
  ({
    [BUTTON_TYPES.PRIMARY_LARGE_FILL]: PLFill,
    [BUTTON_TYPES.PRIMARY_LARGE_OUTLINE]: PLOutline,
    [BUTTON_TYPES.PRIMARY_LARGE_DISABLE]: PLDisable,

    [BUTTON_TYPES.PRIMARY_SMALL_FILL]: PSFill,
    [BUTTON_TYPES.PRIMARY_SMALL_OUTLINE]: PSOutline,
    [BUTTON_TYPES.PRIMARY_SMALL_DISABLE]: PSDisable,
    [BUTTON_TYPES.PRIMARY_SMALL_LINK]: PSLink,

    [BUTTON_TYPES.SECONDARY_LARGE_FILL]: SLFill,
    [BUTTON_TYPES.SECONDARY_LARGE_OUTLINE]: SLOutline,
    [BUTTON_TYPES.SECONDARY_LARGE_DISABLE]: SLDisable,

    [BUTTON_TYPES.SECONDARY_SMALL_FILL]: SSFill,
    [BUTTON_TYPES.SECONDARY_SMALL_OUTLINE]: SSOutline,
    [BUTTON_TYPES.SECONDARY_SMALL_DISABLE]: SSDisable,
    [BUTTON_TYPES.SECONDARY_SMALL_LINK]: SSLink,
  }[buttonType]);

const Button = ({
  children,
  buttonType = BUTTON_TYPES.PRIMARY_SMALL_FILL,
  ...otherProps
}) => {
  const CustomButton = getButton(buttonType);

  return <CustomButton {...otherProps}>{children}</CustomButton>;
};

export default Button;
